version: '3'
services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "3015:80"
    volumes_from:
      - api
    depends_on:
      - api

  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - ./api:/myapp
    networks:
      default:
      horse_race_common_info_network:
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}
      - API_DB_MYSQL_DATABASE=${API_DB_MYSQL_DATABASE}
      - API_DB_MYSQL_USER=${API_DB_MYSQL_USER}
      - API_DB_MYSQL_PASSWORD=${API_DB_MYSQL_PASSWORD}
      - API_DB_MYSQL_HOST=${API_DB_MYSQL_HOST}
      - API_DB_MYSQL_PORT=${API_DB_MYSQL_PORT}
      - TEST_MYSQL_DATABASE=${TEST_MYSQL_DATABASE}
      - TEST_MYSQL_USER=${TEST_MYSQL_USER}
      - TEST_MYSQL_PASSWORD=${TEST_MYSQL_PASSWORD}
      - TEST_MYSQL_HOST=${TEST_MYSQL_HOST}
      - TEST_MYSQL_PORT=${TEST_MYSQL_PORT}
    stdin_open: true
    tty: true
    depends_on:
      - test-db

  api-db:
    build:
      context: ./db/
      dockerfile: Dockerfile
    volumes:
      - horse-race-common-info-api-api-db-store:/var/lib/mysql
      - ./db/initdb.d:/docker-entrypoint-initdb.d
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${API_DB_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${API_DB_MYSQL_DATABASE}
      - MYSQL_USER=${API_DB_MYSQL_USER}
      - MYSQL_PASSWORD=${API_DB_MYSQL_PASSWORD}
    ports:
      - "3307:3307"

  test-db:
    build:
      context: ./api/test_db/
      dockerfile: Dockerfile
    volumes:
      - horse-race-common-info-api-test-db-store:/var/lib/mysql
      - ./api/test_db/initdb.d:/docker-entrypoint-initdb.d
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=${TEST_MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${TEST_MYSQL_DATABASE}
      - MYSQL_USER=${TEST_MYSQL_USER}
      - MYSQL_PASSWORD=${TEST_MYSQL_PASSWORD}

networks:
  horse_race_common_info_network:
    external: true

volumes:
  horse-race-common-info-api-test-db-store:
  horse-race-common-info-api-api-db-store:
