version: '3'
services:
  web:
    build:
      context: ./web/
      dockerfile: Dockerfile
    ports:
      - "3015:80"
    volumes_from:
      - api
    depends_on:
      - api
  api:
    build:
      context: ./api/
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s"
    volumes:
      - ./api:/myapp
    networks:
      - horse_race_common_info_network
    environment:
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - MYSQL_PORT=${MYSQL_PORT}

networks:
  horse_race_common_info_network:
    external: true
